baseurl: "" # the subpath of your site, e.g. /blog
url: "http://php-internals.afup.org" # the base hostname & protocol for your site, e.g. http://example.com

title: "AFUP Lyon"
description: >- # this means to ignore newlines until "baseurl:"
  Antenne AFUP Lyon
twitter_username: AFUP_Lyon
meetup_url: "https://www.meetup.com/fr-FR/afup-lyon-php/"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

feed:
  path: feed

