url: "http://php-internals.afup.org"

title: "AFUP Lyon"
description: >-
  Antenne AFUP Lyon
twitter_username: AFUP_Lyon
meetup_url: "https://www.meetup.com/fr-FR/afup-lyon-php/"

permalink: /posts/:title

ga_ua: "UA-33922307-6"

subheader:
  - label: Appel à speakers
    url: "/cfp"
    icon: bullhorn
  - label: "Historique"
    url: "/historique"
    icon: landmark
  - label: "Newsletter"
    url: "http://eepurl.com/bkOykX"
    icon: "envelope"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Makefile
   - docker-compose.yml
   - docker-compose.override.yml-dist
   - docker-compose.override.yml
   - Gemfile
   - Gemfile.lock

feed:
  path: feed

